### ISSUE TITLE
Test fails when built with make or ninja

### ISSUE THREAD

**Issue by Botched135** [hosseinmoein/DataFrame#102]
Hi!
Updated to the newest version of DataFrame today, and found and issue where ` dataframe_tester_2` fails when built with make or ninja. 
Tried to run the specific test and got the following output:

Testing get_reindexed( ) ... 
Testing get_reindexed_view( ) ...
Testing retype_column( ) ...
Testing load_align_column( ) ...
Testing get_columns_info( ) ...
Testing CategoryVisitor{ } ...
Testing FactorizeVisitor{ } ...
Testing pattern_match( ) ...
Testing ClipVisitor{ } ...
Testing SharpeRatioVisitor{  } ...
Testing RankVisitor{  } ...
Testing SigmoidVisitor{  } ...
Testing combine( ) ...
Testing RSIVisitor{  } ...
dataframe_tester_2: ../modules/DataFrame/test/dataframe_tester_2.cc:846: void test_RSIVisitor(): Assertion fabs(result[idx] - rsi_result[idx]) < 0.0001 failed.

I am compiling with GCC  10.2.0 and running on Manjaro 20.2.1.

**Comment by hosseinmoein** [comment]
There are two reasons that the test programs asserts may fail under different compilers and/or OS's.
1. Some of the algorithms are based on random numbers. The same random generators under different environments generate different numbers even with the same seed.
2. Different environments generate numbers with different precisions. My asserts have hardcoded precision.

Your case, I believe, falls under the second item. If you change the assert statement to
```
assert(fabs(result[idx] - rsi_result[idx]) < 0.001);
```
It should work.
Let me know how it turns out
Thanks

**Comment by Botched135** [comment]
I have tried to change it to different values (0.001-1.0) and the only conclusion I can come to is that debug fails no matter what, and release works even with 0.0001

**Comment by hosseinmoein** [comment]
Sorry I missed this, but the testing (`test_RSIVisitor()`) is done by using random numbers. As I explained on the above, random numbers are different in different environments. You have to skip this test, or print the output and adjust the code to compare to your output.

As to release working fine, in the release version `assert`s are noops.

Thanks
