### ISSUE TITLE
Unresolved external symbol, windows dll

### ISSUE THREAD

**Issue by kv-gits** [hosseinmoein/DataFrame#103]
Some subprojects get this error while building on msvc 2019

`Error	LNK2019	unresolved external symbol "private: static unsigned int hmdf::ThreadGranularity::num_of_threads_" (?num_of_threads_@ThreadGranularity@hmdf@@0IA) referenced in function "public: static unsigned int __cdecl hmdf::ThreadGranularity::get_sensible_thread_level(void)" (?get_sensible_thread_level@ThreadGranularity@hmdf@@SAIXZ)	dataframe_thread_safety`

But I checked project and found there link to DataFrame.lib and the lib file also compiled and placed in lib/Release/DataFrame.lib

Also adding  this code in ,y project

`TDF::set_thread_level(10);`

Causes unresolved external

**Comment by hosseinmoein** [comment]
I don't have access to a Windows compiler, so I cannot reproduce your problem on my side. But this project has been compiled successfully on Windows by many individuals and also by Conan package manager and AppVeyor. It seems that the linking stage of your compile is not happening properly.
So I have a few questions/suggestions in no particular order:

1. How are you compiling this? Are doing it by CMake -- the way It was described in README?
2. If you are not using CMake, make sure the linking part is setup properly to link with DataFrame library. Also, make sure file `ThreadGranularity.cc` is part of the library
2. Make sure you are using C++17 or higher
3. Consider using Conan package manager instead of CMake
4. If you still want to use CMake, look at the AppVeyor log to figure out how they run it. A sample log is here https://ci.appveyor.com/project/hosseinmoein/dataframe

**Comment by kv-gits** [comment]
Release is latest.

1. I need dll so changed my CmakeLists.txt
Added/uncommented this
```
set(BUILD_SHARED_LIBS ON)
set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
...
...
...
add_library(${LIBRARY_TARGET_NAME} SHARED ${${LIBRARY_TARGET_NAME}_SRC})
```
And then I make commands as they are in appveyor logs, but generator is "visual studio 2019"

Got the same external error

**Comment by kv-gits** [comment]
Is it possible to use it without building, just inserting code in project?

**Comment by hosseinmoein** [comment]
Is `ThreadGranularity.cc ` file part of the library?

**Comment by kv-gits** [comment]
> Is `ThreadGranularity.cc ` file part of the library? It is in src/Utils

Sure, of cource checked it and build logs show it
```
HeteroVector.cc
  HeteroView.cc
  HeteroPtrView.cc
  ThreadGranularity.cc
  DateTime.cc
  Generating Code...
```

**Comment by hosseinmoein** [comment]
They should be qualified path:
```
set(${LIBRARY_TARGET_NAME}_SRC
  src/Vectors/HeteroVector.cc
  src/Vectors/HeteroView.cc
  src/Vectors/HeteroPtrView.cc
  src/Utils/ThreadGranularity.cc
  src/Utils/DateTime.cc
)
```

**Comment by hosseinmoein** [comment]
or maybe the inline'ed integer is not the proper way for DLL's. I know little about MS development environment

**Comment by kv-gits** [comment]
> Consider using a static library?

Unfortunately no static, because of Qt project. Only dll, or pure code

**Comment by hosseinmoein** [comment]
Since I don't have access to a windows compiler my help would be limited.
One thing you can do is to take `num_of_threads_` out of the .cc file and put it in the header file as an inline static member

**Comment by kv-gits** [comment]
Thanks! Will try some options and provide info here

**Comment by hosseinmoein** [comment]
FYI, I just pushed a commit to master that eliminated `Utils/ThreadGranularity.cc` file. It was never necessary (it was old style C++). The static data initializations were moved to ThreadGranularity.h as inlines. The CMakeLists.txt file and other make files were changed accordingly.
This may solve your problem

**Comment by kv-gits** [comment]
Temporary solutions is to create "no library" release. But needed to completely rewrite all includes. Seems it is working solution too. Also will try other solution

**Comment by kv-gits** [comment]
> This may solve your problem

Yes, completely solved! Thanks a lot for help and nice lib!
