### ISSUE TITLE
performance test problem

### ISSUE THREAD

**Issue by betaray2016** [hosseinmoein/DataFrame#120]
MacBook> time python test/pandas_performance.py
All memory allocations are done. Calculating means ...
-4.318030613360519e-05, 1.6486147626420655, 1.0000042573786951

real  17m18.916s
user  4m47.113s
sys   5m31.901s

MacBook> time bin/Linux.GCC64/dataframe_performance
All memory allocations are done. Calculating means ...
1, 1.64879, 0.999994

real  4m15.786s
user  2m30.841s
sys   1m36.944s

could u tell me, why the mean of std normal distribution data is 1 in you performance test?? thank you.

**Comment by hosseinmoein** [comment]
That's a good question. The reason is that my defaults are not sensible for all distributions and I used defaults.
If you notice, the last parameter to all random generator functions is an optional parameter. It is `RandGenParams` struct defined in _DataFrameTypes.h_ file. In that struct the default _mean_ is 1 and the default _std_ is 0. So, it turns out that column in DataFrame has all 1s in it.
But that doesn't change the performance measurements.
