### ISSUE TITLE
Issues with get_data and not being able to create an std::array

### ISSUE THREAD

**Issue by idm2114** [hosseinmoein/DataFrame#121]
I am currently creating a DataFrame object from JSON. The creation of the DataFrame works perfectly well, but the next step for me is to try and retrieve an individual row of data. Here’s where things start to break down: because I don’t know the number of columns in the JSON file at compile time (in reality I have a pretty good guess that there will normally be 6 columns, but I want to generalize the program to all N). The function declaration for get_row() states that you need to pass in an object of type std::array that contains the columns’ names. The problem for me is that I currently have a vector of the column names and I cannot figure out how to cast it to an std::array since I won’t know the number of columns at compile time. I’m wondering if there’s a way that I can fix this. Am I using the wrong function? Should I be doing something differently? Fundamentally, the issue is that in the std::array declaration N must be known at compile time, but I can’t figure out how to work around that. Any help would be greatly appreciated! 

Also, just out of curiosity, why can’t an std::vector be used for the columns input?

EDIT: Feel free to disregard, I fixed my issue by using get_data_by_loc(). My apologies. Thanks for making this project, by the way, it's super useful!

**Comment by hosseinmoein** [comment]
I never personally needed/used the get_row() method. Maybe that's why I didn't think about it too deeply. The only reason for using _std::array_ was that it is the most efficient container. It is the closest to having variadic template arguments. 
Of course, you need to know all the types at compile time. But that is always the case.

I can either add anothert get_row() with _std::vector_ or just have a get_row() that takes no arguments and includes all the columns in the row. I probably do the latter.

Hopefully, I can do this over the weekend

**Comment by hosseinmoein** [comment]
@idm2114 , `get_row()` with no column name arguments is implemented in master

**Comment by idm2114** [comment]
Amazing, thank you so much! Again, I really appreciate your work with this repo.
