### ISSUE TITLE
How can I add a new index, and assign new values to the row at the new index?

### ISSUE THREAD

**Issue by yuxiaojian01** [hosseinmoein/DataFrame#144]
I added a new index to the dataframe with columns = {"type", "mkt",....}, and added a value to the column "type","mkt",etc, like:
`df.append_index("000001.SZ");`
    `df.get_column<std::string>("type")[df.get_index().size()-1] = "default";`
    `df.get_column<std::string>("mkt")[df.get_index().size()-1] = "SZ";`
`.....`
But when I print the dataframe df, I found the "type","mkt" columns does not update at the new index. They are all null values at the the new index. 
So, how to add a new index to a dataframe, and update the columns' values corresponding to the new index?
Thank you very much.

**Comment by hosseinmoein** [comment]
This is not how you add values to a column. The `get_column()` is meant to be for read-only access or changing the existing values. It is not meant to extend the column (in any case your code should result in a crash, since the length of the column is really not extended). This is a hole in DataFrame interface that I plan to fix.

Just like adding to the index, there are `append_column()` methods you can use.
