### ISSUE TITLE
No write to file example

### ISSUE THREAD

**Issue by federicomartinlara1976** [hosseinmoein/DataFrame#242]
The hello_world.cc example has no use of write to csv file method.

**Comment by hosseinmoein** [comment]
I didn't want to write to a file in hello world because I was cautious about messing up the user filesystem which I don't know anything about.
Code sample for all functions are in the docs here: https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/DataFrame.html

**Comment by federicomartinlara1976** [comment]
Anyway, i have checked and this format for csv is not suitable for my example. Thank you

**Comment by hosseinmoein** [comment]
You probably want the `csv2` format which is similar to Pandas csv format

**Comment by federicomartinlara1976** [comment]
Thank you. I'll test the format that recommend.
