### ISSUE TITLE
do you have any performance test compare with python pandas?

### ISSUE THREAD

**Issue by backtradercn** [hosseinmoein/DataFrame#31]
do you have any performance test compare with python pandas?

**Comment by hosseinmoein** [comment]
I don't. But if you have the means to do a meaningful comparison in terms of both performance and scale-ability, it would be great.
Also @yssource

**Comment by yssource** [comment]
pandas is developed with python, which is absolutely slower then C/C++.
For performance reasons, I decided to replace the algorithm part of my python codes with C++ DataFrame. 
And then I use `pybind11` porting back to python.

@backtradercn 
For a simple speed testing, maybe it will help you.
1. python `timeit` module
`import timeit `
2. c++ Boost `timer` 
`#include<boost/timer.hpp>`

**Comment by hosseinmoein** [comment]
@backtradercn, @yssource 
I have added a performance section to the README file explaining how the new performance test runs

**Comment by qingtiandalaoye** [comment]
MacBook> time python pandas_performance.py
All memory allocations are done. Calculating means ...

real  17m18.916s
user  4m47.113s
sys   5m31.901s
MacBook>
MacBook>
MacBook> time ../bin/Linux.GCC64/dataframe_performance
All memory allocations are done. Calculating means ...

real  6m40.222s
user  2m54.362s
sys   2m14.951s


---seems cpp only 2 times faster than python?

**Comment by hosseinmoein** [comment]
@qingtiandalaoye,
I think you are misinterpreting the specs, probably because I wasn’t clear in my writeup. A few points:

1. The Pandas performance script is not really in Python. I believe almost everything there is done in Numpy which is C. That means DataFrame is more than 2x faster the Numpy/C.
2. As I mentioned in “The interesting part” section, DataFrame is more than 2x faster than Pandas/Numpy in generating the same random numbers and loading them into column vectors. But DataFrame was about 10x faster in calculating means.
3. You only load data once but calculate statistics many times. So in general DataFrame is about 10x faster than parts of Pandas that are in Numpy. Parts of Pandas that are purely in Python should be much much slower.
