### ISSUE TITLE
Add DataFrame library to a package manager

### ISSUE THREAD

**Issue by YannickLecroart** [hosseinmoein/DataFrame#59]
Hi,

It could be a good idea to add the library to a package manager such as Vcpkg or Conan as this would increase the module adoption.

Regards,

**Comment by hosseinmoein** [comment]
@yssource was attempting to add conan.
yssource, is that still feasible?

**Comment by yssource** [comment]
It was approved by reviewers, but may be waiting one day or more to merge into the conan-center-index.

https://github.com/conan-io/conan-center-index/pull/803

And after the merged, I will add how to use DataFrame by conan package in README.md.

`conan install dataframe/1.7.0@`

**Comment by hosseinmoein** [comment]
@yssource, How does this work
For each release/commit, do you have to get re-certified? 
Or if you give me a pull request and I merge it we are done?

**Comment by yssource** [comment]
- [creating a package](#org499e0eb)
- [using a package](#orgf008f2f)

Perhaps now Europe is affected by the COVID-19, and the conan members have slowed down their works.

conan have two concepts, creating a package and using a package.

What I do is creating a package for DataFrame <https://github.com/conan-io/conan-center-index/pull/803>.


<a id="org499e0eb"></a>

# creating a package
There is not re-certified, but if you wanna do a contribution for conan-center-index, first write <https://github.com/conan-io/conan-center-index/issues/4> to request access. Then, you would PR a conan package for a cpp project.

All of their packages they have already created are listed here. <https://github.com/conan-io/conan-center-index/tree/master/recipes>

These packages are very good examples to learn how do a conan package for c++ project.

And some projects conan have been working on https://github.com/conan-io/conan-center-index/issues/621

The conan package is created based on the c++ release source, but you could do a patch for it if you wanna do a mortification base on the original author's release. Why there is a patch, because conan-center-index has some needs of their own's. For instance, removing the docs and testing binaries, which are not the content of a conan package.


<a id="orgf008f2f"></a>

# using a package

How to use a package, here some examples <https://github.com/conan-io/examples/tree/master/libraries>

If your project wanna depends a 3rd package, which is already created by conan-center-index, you could write a [conanfile.txt](https://docs.conan.io/en/latest/reference/conanfile_txt.html?highlight=conanfile) or [conanfile.py](https://docs.conan.io/en/latest/reference/conanfile.html?highlight=conanfile) to [consume it](https://docs.conan.io/en/latest/using_packages/conanfile_txt.html).

And actually, the test_package is a *trivial part* of using the package.

DataFrame is the original c++ source, and it has no 3rd depends. I just create a conan package on conan-center-index. If a user wanna using the dataframe conan package, what the user needs to do is just write a conanifle.py on their own's project.
It would be better to tell the user how to use DataFrame by conan in the Readme.

**Comment by yssource** [comment]
https://github.com/hosseinmoein/DataFrame/pull/61

**Comment by yssource** [comment]
[conan install dataframe/1.8.0@](https://github.com/conan-io/conan-center-index/pull/1176)

v1.8.0 is OK also.

**Comment by remz1337** [comment]
Hello,

anyway to get this on vcpkg?

Thanks

**Comment by hosseinmoein** [comment]
Currently no. In general I am somewhat not an expert in Windows environment.
If you know how to put it in the vcpkg and willing to contribute, I will appreciate it
