### ISSUE TITLE
Writing DataFrame in csv file and loading it in Pandas

### ISSUE THREAD

**Issue by stefan-gavranovic** [hosseinmoein/DataFrame#70]
I have used one of the test examples for following case scenario: 

1. Write DataFrame content to csv/json file 
2. Load that file using python pandas. 

And I expected to have same DataFrame in both cases.

Here is the code I used on c++ side. 

```c++
    std::vector<unsigned long> idx = {123450,
                                      123451,
                                      123452,
                                      123453,
                                      123454,
                                      123455,
                                      123456,
                                      123457,
                                      123458,
                                      123459,
                                      123460,
                                      123461,
                                      123462,
                                      123466};
    std::vector<double>        d1  = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
    std::vector<double>        d2  = {8, 9, 10, 11, 12, 13, 14, 20, 22, 23, 30, 31, 32, 1.89};
    std::vector<double> d3 = {15, 16, 17, 18, 19, 20, 21, 0.34, 1.56, 0.34, 2.3, 0.1, 0.89, 0.45};
    std::vector<int>    i1 = {22, 23, 24, 25, 99, 100, 101, 3, 2};
    MyDataFrame         df;

    df.load_data( std::move( idx ),
                  std::make_pair( "col_1", d1 ),
                  std::make_pair( "col_2", d2 ),
                  std::make_pair( "col_3", d3 ),
                  std::make_pair( "col_4", i1 ) );

    std::ofstream outfile;
    outfile.open( "file.json", std::ios_base::in | std::ios_base::trunc );
    df.write<std::ostream, double, int>( outfile, false, io_format::json );
```

Once file is loaded using pandas, following table is obtained:

![image](https://user-images.githubusercontent.com/35734157/84508104-168a0b80-acc2-11ea-8414-cb67a877014d.png)

Is this expected behaviour?

**Comment by hosseinmoein** [comment]
Yes, this is expected
The json/csv formats of DataFrame are somewhat different from Pandas for a few reasons:
1.	In C++ I need to store the type specification per column
2.	I also store the number of items per column for memory and speed efficiency
3.	I store the data row-wise again for efficiency and simplicity of reading/writing data

I had thought about this, before I implemented it. And I believe to be compatible/exchange data with Pandas we should go with Arrow database solution.
I haven’t had time to implement reading/writing from arrow. I would love to find a contributor to do that, since I have very limited time

Best,

**Comment by stefan-gavranovic** [comment]
Thanks a lot for a quick reply, that would be very useful feature. In the meantime I can just do some post-processing. 
Unfortunately, I have no time to contribute to your project, though it would be very interesting.

**Comment by nanoric** [comment]
How about adding an option to product pandas compatible outputs?
For example, store all these imformation in another file?
```
write_pandas_compatible("path_to.csv", "path_for_meta.dat")
```

**Comment by hosseinmoein** [comment]
This is an old issue. Since then, I have added a new option to write() (io_format::csv2) that writes the data very similar to Pandas


Sent from the all new AOL app for iOS


On Thursday, June 17, 2021, 1:03 AM, nanoric ***@***.***> wrote:




How about adding an option to product pandas compatible outputs?
For example, store all these imformation in another file?
write_pandas_compatible("path_to.csv", "path_for_meta.dat")
