### ISSUE TITLE
Question on the implementation of erase

### ISSUE THREAD

**Issue by nehcuh** [hosseinmoein/DataFrame#81]
Hi, Hosseinmoein,

Method of `erase` of standard vector returns an iterator points the next element of element been erased. In `VectorPtrView.h`, you've realized the erase function which returns `void`, is there some consideration why you did this?

**Comment by hosseinmoein** [comment]
Yes, the consideration was to make the code simpler. Note that these vectors are for DataFrame internal use. They are not meant to be general purpose objects.
Returning an iterator from the erase makes the code a lot more complicated, since the underlying vector iterator points to a data pointer. Furthermore, I did not need this behavior in DataFrame
