### ISSUE TITLE
Printing a data set

### ISSUE THREAD

**Issue by SammieH21** [hosseinmoein/DataFrame#87]
Hello, I've searched for the answer to this question, but I didn't find anything definitive. How do we print the contents of a DataFrame using your library?

**Comment by SammieH21** [comment]
Nevermind, I figured out that 
`dfx.write<std::ostream,` int, double, std::string>(std::cout);'
 provided printed out the data set. Any neater way to display the output of a dataset?

**Comment by hosseinmoein** [comment]
@SammieH21 ,
`write()` method has a second parameter which is `io_fomrat`:
https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/write.html
https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/io_format.html

Currently, it supports two formats `csv` and `json`. The csv format is different from regular csv because in here I need to keep track of column types and also this format was easier to code.
I was planning to add a regular csv format (more similar to Pandas) as `csv2` as time allows (I hardly have time to work on it). I am also looking for contributors. If you feel up to it, please let me know. Otherwise, I try to add it in not so distant future.

**Comment by hosseinmoein** [comment]
@SammieH21 ,
I added the `io_format::csv2` which prints the DataFrame very similar to Pandas csv format. In other words `io_format::csv2` is the transpose of `io_format::csv`.
Please see documentation and examples here
```
https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/io_format.html
https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/read.html
https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/write.html
```

**Comment by SammieH21** [comment]
Awsome! Many thanks for your efforts! Once I become more proficient in C++, I'd be willing to help in the process of building its functionality, overall, excellent package!
